# Configuración base de la aplicación.
config_insumos:
  path_insumos: "Insumos/"

  base_vtas: 
    nom_base: "Consulta Diaria Ventas - Snackeros.xlsx"
    nom_hoja: "Consolidado"
    cols_vtas: &cols_vtas
      anio_mes: "Año/Mes"
      tipo_venta: "Tipo de Venta"
      oficina_ventas: "Oficina de ventas"
      cliente_clave: "Cliente - Clave"
      cliente: "Cliente"
      codigo_ecom: "Código ECOM"
      agente_comercial_clave: "Agente Comercial - Clave"
      agente_comercial: "Agente Comercial"
      venta_dinero: "Venta $"
      venta_kg: "Venta KG"
      venta_un: "Venta UN"

  drivers:
    nom_base: "Drivers.xlsx"    
    nom_hoja: "DRIVERS"
    cols_drivers: &cols_drivers
      regional: "Regional"
      cod_sap: "Cod SAP"
      nom_agente_comercial: "Nombre Agente Comercial"
      cambio_cod_ecom_crm: "Cambio Cod ECOM a CRM"
      mes: "Mes"
      cod_cliente: "Cod Cliente"
      cod_actual: "Cod Actual"
      cod_jefe_ventas: "Cód. Jefe de Ventas"
      jefe_ventas: "Jefe de Ventas"
      cod_cliente_alt: "Cod Cliente.1"
      concat: "CONCAT"

dict_cols:
  cols_ventas: *cols_vtas
  cols_drivers: *cols_drivers
  status: "STATUS"
  cod_ecom_final: "COD ECOM FINAL"
  cod_ac_final: "COD AC FINAL"
  nombre_ac_final: "NOMBRE AC FINAL"

Resultados:
  path_resultado: "Resultados\\"

